### ISSUE TITLE
Bug: Flax & Barley Displaying Dead

### ISSUE THREAD

**Issue by Qrylor** [smallo92/PlantGrowProgress#1]
Planted Flax & Barley in the Plains is reporting: _"Can't grow in this environment"_ and turns problem brown.
Removing PlantGrowProgress reverts to expected reporting / healthy.

**Comment by smallo92** [comment]
Not sure how that's possible since I'm not touching anything related to that at all

**Comment by smallo92** [comment]
Actually shit, I may have accidently left some debug code in. I'll fix it in an update. My bad.

**Comment by smallo92** [comment]
latest version had this fixed
