### ISSUE TITLE
[Feature Request] Add Bushes Back

### ISSUE THREAD

**Issue by SteveKnowless** [smallo92/PlantGrowProgress#2]
First thank you for this mod. It has helped with a ton of things and just made the game more enjoyable. I have not updated to the latest version because I see that you have removed the Bush %. Although I see that the timer is slightly off I think it is an amazing feature to have and not something that really bothers me personally. Is it possible for you to add it back and then perhaps add a config file to disable it if people dont want it to be shown? Thanks again so much!

**Comment by smallo92** [comment]
> Although I see that the timer is slightly off

It wasn't "slightly off" it was 100% broken and not showing a number even remotely close. I won't be adding it back until it's perfect.

**Comment by smallo92** [comment]
It's back in the latest version, turns out it was a Valheim issue causing the progress to restart it. Have included a patch to fix it.

**Comment by SteveKnowless** [comment]
Thank you. I was going to say I personally did not see it 100% broken. What you described is exactly what is happening in game. If i stay near a bush it grows, if I leave and come back its 0% and starts all over. Thanks for adding it back. Take care!
