### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bruninjaman** [smallo92/PlantGrowProgress#3]
I tried it with multiple other mods couldnt make it work
set all the configuration files to be sure, still not worked
tried to remove all other mods and try this one alone, still not worked..
it seems that the game update broke the mod.

**Comment by smallo92** [comment]
Nope, still works fine. Something wrong on your end. Make sure your BepInEx is updated.

![Image](https://fivem.fail/rdr3/Bounty/N_0x12e981d53b07bf48/q7XZnGL8G1.png)

**Comment by bruninjaman** [comment]
thanks and sorry, I reported the wrong mod it was 'crop replant'.
